kind: Service
apiVersion: v1
metadata:
  name: shinobi-service
  namespace: shinobi
spec:
  selector:
    app: shinobi
  type: ClusterIP
  ports:
    - name: 8080tcp8080-shinobi
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinobi-app
  namespace: shinobi
  labels:
    app: shinobi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinobi
  template:
    metadata:
      labels:
        app: shinobi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: shinobi
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
