kind: Service
apiVersion: v1
metadata:
  name: shinobi-service
spec:
  selector:
    app: shinobi
  type: ClusterIP
  ports:
    - name: 8080tcp8080-shinobi
      protocol: TCP
      port: 8080
      targetPort: 8080
